### ISSUE TITLE
cursor not visible in text boxes

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#1]
Every input field is affected (like this one I am filling in ATM).
I am on webkit-gtk-2.12.2 and gtk+-3.20.2.

**Comment by aidanholm** [comment]
I have this issue as well, not sure why this is happening yet.

**Comment by ff2000** [comment]
Could it be that somewhere in handling modes the focus is not given correctly to the active widget? Is there something like an "input widget" in gtk that needs to be set?

**Comment by aidanholm** [comment]
Fixed; thanks for the hint. There's still a minor issue where insert mode isn't entered automatically when elements are focused with JavaScript.
