### ISSUE TITLE
«Try again» button reloads wrong page

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#100]
1. run: ./luakit -U https://duckduckgo.com
2. when the page loaded, press 'o' and type 'nosuchurl.nosuchurl', enter
3. standard error message is shown: «A problem occurred while loading the URL http://nosuchurl.nosuchurl/», there is a button «Try again»
4. note location is «https://duckduckgo.com/» in status bar
5. press «Try again»
6. it reloads the previous duckduckgo.com page

what I would expect:
1. «Try again» reloads the URL shown in the error message (nosuchurl.nosuchurl in the example above)
2. when error message is displayed, status bar shows the URL it tried to load (nosuchurl.nosuchurl)

it is not new, but to be precise, build from 8e813f7094fdaba0a13a410c187fa4f232b0f5b0 tested

**Comment by aidanholm** [comment]
Issue starts at a43f97c, caused by fix for #96. I was wondering what would break.

**Comment by aidanholm** [comment]
Fix pushed at 44c24e8; both this issue and #96 are resolved. The downside is that the `property::uri` signal is spammed a bit more.
