### ISSUE TITLE
Touchpad two-finger scrolling freezes

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#134]
no stable way to reproduce found so far, but occasionally two-finger scrolling stops working

hovering pointer upon URLs does update status line, clicking text does cause text to be highlighted, everything seems working properly except two-finger scrolling (that is no more then sending button 4 and 5 events apparently)

it happens only to luakit and scoped to a window (stops working in one, but still fine in others)

touchpad scrolling can easily be restored if scrolling with keyboard — seems any navigation key is fine

**Comment by Ygrex** [comment]
yes, did not see this issue before multi-processing introduced

**Comment by aidanholm** [comment]
Yep, i've experienced this issue myself --- pretty weird. I believe WebKit handles touchpad scrolling; luakit never sees the button events.

**Comment by aidanholm** [comment]
@Ygrex Are you still experiencing this issue? I can't remember the last time it happened to me; it may have been fixed upstream.

**Comment by Ygrex** [comment]
I am not, this looks like fixed

**Comment by aidanholm** [comment]
Great! I'll close this now then
