### ISSUE TITLE
Manpage mentions inexistent :viewsource command

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#141]
building from 44a4b03 produces luakit.1 manpage:

```
$ man --nj ./luakit.1.gz | grep :viewsource -A1
       :viewsource
              Display page source code.  Use :viewsource! to toggle off.
```

trying it in browser produces:

```
Error: Not a browser command: "viewsource"
```

**Comment by aidanholm** [comment]
Thanks; Should be `:view-source`

**Comment by aidanholm** [comment]
Fixed at b1ea552

**Comment by Ygrex** [comment]
right… I should have mentioned that the second part: «Use :viewsource! to toggle off.» has no alternative anymore apparently, «vs» and «vs!» are identical as far as I can see

**Comment by aidanholm** [comment]
The webkit 2 implementation is  very rudimentary at the moment... opened a separate issue #144
