### ISSUE TITLE
Cannot copy text from popup error messages

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#143]
two recently reported issues mention popup error message:
https://github.com/aidanholm/luakit/issues/141
https://github.com/aidanholm/luakit/issues/142

text of such messages cannot be copied so that I re-typed it by hands

the expected interface is something like: highlight text with a pointer, click right button and choose «Copy»

**Comment by aidanholm** [comment]
Sorry about the inconvenience; should be easy to fix

**Comment by aidanholm** [comment]
Fixed at 4d86708
