### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by aidanholm** [aidanholm/luakit#195]
This fork has diverged enough that a new website would be desirable.
Would be nice to have Lua API docs online (#194)

**Comment by JR1994** [comment]
would that require renaming the browser or just getting a new domain for it?

**Comment by aidanholm** [comment]
I'll probably use GitHub pages for the forseeable future. Not considering a name change at this point. The point of a new website is that most information online about the original Luakit no longer applies. It'd also be nice to have a place to announce when people need to resync their config files to prevent breakage, which is currently a problem whenever I edit files in `config/`.

**Comment by aidanholm** [comment]
New website up at http://aidanholm.github.io/luakit/. Good enough for now.
