### ISSUE TITLE
Changing the default zoom level gives error: attempt to index global 'webview' (a nil value)

### ISSUE THREAD

**Issue by i47i** [aidanholm/luakit#197]
When I add the following to rc.lua in the correct location after require "webview" and before the comment "End user script loading" it gives an error.

webview.init_funcs.set_default_zoom = function (view, w)
  view.full_content_zoom = true -- optional
  view.zoom_level = 1.5 -- a 50% zoom
end

The above code was found in the old luakit FAQ at https://github.com/luakit/luakit/wiki/Frequently-Asked-Questions and the error is:

[    0.236515] W: luaH_dofunction:157: error in /home/i47i/.config/luakit/rc.lua:165: attempt to index global 'webview' (a nil value)
stack traceback:

Luakit fails to start after the error.

This is probably not a bug but caused by my lack of understanding lua. The above does work with the old stable luakit circa 2012 using the old webkitgtk. However it doesn't work with a recent pull from here and using webkit2gtk-2.14.5

The solution is probably trivial, and I would very much appreciate it if someone would point it out to me.

**Comment by aidanholm** [comment]
`webview` is no longer global. To fix your error, change `require "webview"` to `local webview = require "webview"`. This was a fairly recent change; a lot of other things are no longer global.

**Comment by aidanholm** [comment]
You could also add a domain_props rule with your zoom level customizations. I'm planning to deprecate `webview.init_funcs` and `window.init_funcs` eventually (see #191 for rationale).

Separately, I'll add the `local webview = ` fix to the default config.

**Comment by i47i** [comment]
Changing `require "webview"` to `local webview = require "webview"` fixed it perfectly.

Thank you for your helpful reply.
