### ISSUE TITLE
Build failure: javascriptcoregtk-3.0 not found

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#2]
I am on webkit-gtk-2.12.2 and gtk+-3.20.2 and for me this is "javascriptcoregtk-4.0". As 3.0 seems to be OK for you (and you obviously use gtk3 and webkit4) I didn't create a PR as I just don't know for which gtk/webkit-gtk versions to check for.

**Comment by aidanholm** [comment]
Is this when building for WebKit2? I've just pushed a change to config.mk, and javascriptcoregtk-4.0 should now be used for builds with USE_WEBKIT2=1

**Comment by ff2000** [comment]
Thx, the commit fixed my issue :+1:
