### ISSUE TITLE
[Adblock] how to init?

### ISSUE THREAD

**Issue by myf** [aidanholm/luakit#219]
trying to use adblock. added 
`require 'adblock'`
`require 'adblock_chrome"`
in confg

according to the file descriptions i will ahve to download `easylist.txt` to `.local/share/luakit/adblock`, but after that the program failed with error message

> [    0.046168] E: luaH_dofunction:157: ./lib/adblock.lua:384: attempt to index local 'list' (a nil value)
stack traceback:
	./lib/adblock.lua:482: in main chunk

did i do anything wrong?

**Comment by aidanholm** [comment]
From reading the code, I'd guess you don't have a `subscriptions` file or an entry in that file for `easylist.txt`. A valid entry would look like `easylist.txt\t\tEnabled` (replacing `\t` with actual tabs). Opened #220 for this bug (it shouldn't have errors). The adblock loading code is pretty brittle and i'll probably clean it up soon.
