### ISSUE TITLE
Reuse the info bar for prompt instead of using a new widget

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#25]
For me some webpages (e.g. spiegel.de and focus.de) resize extremely slowly. Hitting `:` or any shortcut that pops up the prompt resizes the webview which leads to a lag of several seconds. Closing the prompt does the same thing. Of course webkit-gtk should not take that much time in the first place...

vimperator uses the same bar for showing the current status (url, links hovered, tab status, ...) and prompt.

**Comment by aidanholm** [comment]
This would probably be good, but the info bar is a hbox of label widgets, while the input bar is an entry widget; it should be possible to pack them both within a hbox and only show one at a time, but there'd have to be a way to ensure they had the same height, and that you could show one and hide the other without causing a re-layout. I'll look into it.

**Comment by ff2000** [comment]
An alternative would be to place the prompt above the info bar as a floating widget. That way no resize is triggered.

**Comment by aidanholm** [comment]
I've pushed a change that replaces the status bar with the input bar; let me know if you still have lag.

**Comment by ff2000** [comment]
Wow! The prompt now appears instantaneously! I now see that it even lagged for about:blank... Big thanks!

**Comment by ff2000** [comment]
Need to reopen this issue, because now the completion popup (when pressing <TAB> inside the prompt) is causing the geometry change. I think is was a popup before.

**Comment by ff2000** [comment]
Eek, seems I'm wrong. git reset to the last version I used and it seems this has been like that before. So could the completion be made a popup?

**Comment by aidanholm** [comment]
It's now overlaid over the main webview widget; should look the same, but won't cause a page resize.

**Comment by ff2000** [comment]
Gave it a good test this time and it seems to work. Great job, thx!
