### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by SolarAquarion** [aidanholm/luakit#255]
mkdir doc/apidocs
./luakit --log=error -c build-utils/docgen/process.lua > doc/apidocs/module_info.lua

** (luakit:17554): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[    0.122514] E: luaH_dofunction:157: /usr/share/luakit/lib/adblock.lua:347: Cannot read subscriptions from non-existent file
                  Traceback:
                  (1) [C]                                   in function assert
                  (2) /usr/share/luakit/lib/adblock.lua:347 in function read_subscriptions
                  (3) /usr/share/luakit/lib/adblock.lua:361 in function load
                  (4) /usr/share/luakit/lib/adblock.lua:462 in main chunk
                  (5) [C]                                   in function require
                  (6) build-utils/docgen/process.lua:20     in function get_mode_bindings_for_module
                  (7) build-utils/docgen/process.lua:47     in main chunk
[    0.122537] F: main:215: couldn't find rc file
make: *** [Makefile:71: apidoc] Error 1

**Comment by SolarAquarion** [comment]
** (luakit:26058): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[    0.058579] E: luaH_dofunction:157: build-utils/docgen/process.lua:5: module 'window' not found:
                  	no field package.preload['window']
                  	no file './window.lua'
                  	no file '/usr/share/luajit-2.0.4/window.lua'
                  	no file '/usr/local/share/lua/5.1/window.lua'
                  	no file '/usr/local/share/lua/5.1/window/init.lua'
                  	no file '/usr/share/lua/5.1/window.lua'
                  	no file '/usr/share/lua/5.1/window/init.lua'
                  	no file '/home/solaraquarion/.config/luakit/window.lua'
                  	no file '/home/solaraquarion/.config/luakit/window/init.lua'
                  	no file '/etc/xdg/luakit/window.lua'
                  	no file '/etc/xdg/luakit/window/init.lua'
                  	no file '/usr/share/luakit/lib/window.lua'
                  	no file '/usr/share/luakit/lib/window/init.lua'
                  	no file './window.so'
                  	no file '/usr/local/lib/lua/5.1/window.so'
                  	no file '/usr/lib/lua/5.1/window.so'
                  	no file '/usr/local/lib/lua/5.1/loadall.so'
                  Traceback:
                  (1) [C]                              in function require
                  (2) build-utils/docgen/process.lua:5 in main chunk
[    0.058606] F: main:215: couldn't find rc file

**Comment by aidanholm** [comment]
I was getting a different error, but the basic issue is that build-utils/docgen/process.lua assumes DEVELOPMENT_PATHS=1. I've pushed a fix for that issue and can build it again; let me know if it fixes this.

**Comment by SolarAquarion** [comment]
enerating 'doc/apidocs/modules/adblock.html'...
luajit: build-utils/docgen/gen.lua:22: module 'markdown' not found:
	no field package.preload['markdown']
	no file './markdown.lua'
	no file '/usr/share/luajit-2.0.4/markdown.lua'
	no file '/usr/local/share/lua/5.1/markdown.lua'
	no file '/usr/local/share/lua/5.1/markdown/init.lua'
	no file '/usr/share/lua/5.1/markdown.lua'
	no file '/usr/share/lua/5.1/markdown/init.lua'
	no file 'build-utils/markdown.lua'
	no file './markdown.so'
	no file '/usr/local/lib/lua/5.1/markdown.so'
	no file '/usr/lib/lua/5.1/markdown.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	build-utils/docgen/gen.lua:22: in function 'format_text'
	build-utils/docgen/gen.lua:226: in function 'generate_binds_and_modes_html'
	build-utils/docgen/gen.lua:274: in function 'generate_doc_html'
	build-utils/docgen/gen.lua:340: in function 'generate_module_html'
	build-utils/docgen/gen.lua:411: in function 'generate_documentation'
	./build-utils/docgen/makedoc.lua:88: in main chunk
	[C]: at 0x00404750
make: *** [Makefile:72: apidoc] Error 1
 Another one

**Comment by aidanholm** [comment]
Fixed at 7687f255; caused by only searching for system markdown.lua, which I happen to have for some reason.

**Comment by SolarAquarion** [comment]
i mean i decided to wget markdown.lua and added it to the srcdir in build

**Comment by SolarAquarion** [comment]
so this set of build issues stopped

**Comment by aidanholm** [comment]
Yes I noticed that; it should no longer be necessary. Sorry for the inconveniences. I'm planning to set up a minimal Arch VM to test installation before I push updates; that should prevent this sort of thing from happening again.
