### ISSUE TITLE
Search on bugzilla broken

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#26]
Any search on bugzilla-driven issue trackers (tested bugs.gentoo.org, bugs.kde.org and bugs.gnome.org) results in the following error and a save file dialog for buglist.cgi.

```
Unable to load page
A problem occurred while loading the URL https://bugs.gentoo.org/buglist.cgi?chfield=%5BBug%20creation%5D&chfieldfrom=7d&list_id=3193658&order=bug_id&query_format=advanced
Frame load was interrupted
```

AFAIR bugzilla has worked in the past with luakit.

**Comment by aidanholm** [comment]
Some things have broken recently --- downloading appears to be another of them --- and I haven't yet had time to track down why, but it appears to be related to this error.

**Comment by aidanholm** [comment]
I cannot reproduce this; are you still experiencing this issue?

**Comment by ff2000** [comment]
I can't either, so "something" got fixed by some commit recently :)
Thx!
