### ISSUE TITLE
follow mode not working

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#3]
Pressing f/F will pop up a box in the bottom. But whatever I enter there nothing happens. Also I can't see any overlay in the web view, which I expected. Is it just an issue with the webkit version I am using or is it not supposed to work yet?

I am on webkit-gtk-2.12.2 and gtk+-3.20.2.

**Comment by aidanholm** [comment]
Some Lua modules in the webkit2 branch, including follow.lib, are broken for a WebKit 1 build. Follow mode should work for a WebKit 2 build however.

**Comment by ff2000** [comment]
webkit-gtk-2.12.2 AFAIK completely dropped webkit1, so according to your comment it should work, but it unfortunately doesn't. I currently still run default configs, DEVELOPMENT_PATHS turned on.
Is there a good way to debug lua?
((I'm running awesome WM since quite some time now (years...) but never got deeper into lua than what I needed to adjust the config to my needs...))

**Comment by aidanholm** [comment]
Run the web browser from a terminal, and you should get any Lua error messages in your stdout/stderr. You can evaluate Lua directly from the `:lua` command, as long as it returns something (that command is very hacky). An idea I've been considering is a lua introspector as a chrome page, maybe something that shows a tree of Lua values, with the root showing global variables and packages?

**Comment by ff2000** [comment]
I already thought that there should be errors on the terminal, but there are none. The only message that I see is "changed signal raised with text" while typing. I also tried `:lua` but failed ;) (got an error) - will look into that again. A lua inspector definitely would be great!

**Comment by aidanholm** [comment]
Probably the easiest way for now is to sprinkle print() calls throughout the Lua code; I'll probably start work on a Lua inspector soon

**Comment by ff2000** [comment]
On Tue, 07 Jun 2016 00:45:34 -0700, Aidan Holm notifications@github.com wrote:

> Probably the easiest way for now is to sprinkle print() calls throughout the Lua code; I'll probably start work on a Lua inspector soon

Problem found.
msg.c:134 sets the extension_directory to the LUAKIT_INSTALL_PATH, which is /usr/local/share/luakit.
I was running luakit directly from the build directory, without installing luakit ever to the system, so the web extension was not found. Could this be made to work with DEVELOPMENT_PATHS=1?
(After hardcoding the dir to my source directory follow mode is working, btw. :))

**Comment by ff2000** [comment]
This patch works (tested only with DEVELOPMENT_PATHS=1), but I am not sure about the "./" thing, probably there is a better solution like "gtk_application_path()" or similar...

``` patch
diff --git a/msg.c b/msg.c
index 7202d59..e72c44b 100644
--- a/msg.c
+++ b/msg.c
@@ -131,7 +131,12 @@ initialize_web_extensions_cb(WebKitWebContext *context, gpointer UNUSED(user_dat
 {
     const gchar *socket_path = g_build_filename(globalconf.cache_dir, "socket", NULL);
     /* const gchar *extension_dir = "/home/aidan/Programming/luakit/luakit/"; */
-    const gchar *extension_dir = LUAKIT_INSTALL_PATH;
+#if DEVELOPMENT_PATHS
+ #define LUAKIT_WEBEXT_DIR "./"
+#else
+ #define LUAKIT_WEBEXT_DIR LUAKIT_INSTALL_PATH
+#endif
+    const gchar *extension_dir = LUAKIT_WEBEXT_DIR;

     /* Set up connection to web extension process */
     g_thread_new("accept_thread", web_extension_connect, (void*)socket_path);
```

**Comment by aidanholm** [comment]
Ah yep, makes sense; just `"."` would _probably_ be fine, but to be on the safe side there's `g_get_current_dir()` which should do the trick. I'll fix that tomorrow.

**Comment by aidanholm** [comment]
Fix pushed

**Comment by ff2000** [comment]
Thx, it works :)
The GLib manual says, that the returned path must e freed. Not idea how critical this is (to you ;))
Going to close this nevertheless.

**Comment by aidanholm** [comment]
Whoops, thanks for catching that.
