### ISSUE TITLE
Sluggish performance

### ISSUE THREAD

**Issue by aidanholm** [aidanholm/luakit#33]
Notably, tab switching taking longer than usual and tab list widget not updating immediately after a tab switch.

**Comment by ff2000** [comment]
On Mon, 20 Jun 2016 05:11:19 -0700, Aidan Holm notifications@github.com wrote:

> Notably, tab switching taking longer than usual and tab list widget not updating immediately after a tab switch.

I had a quite unusable interface when the web process was busy with google maps. If your issue is also caused by a busy web process the solution could be to switch process model to one web-process per view.

**Comment by aidanholm** [comment]
Unlikely to be related; I've been running 77bf25b for a few days with no sluggishness at all; the current master slows down within minutes of use. I'll try to find the sluggish commit by bisecting.

Separately, one process per view would be nice, but it has its own issues; plugin architecture will need to be rethought a little, and webview initialization time becomes longer; opening a new tab takes a good 0.3-0.5 seconds longer. A C-side webview cache could help with that though... hmmm...

**Comment by aidanholm** [comment]
Fixed; caused by noscript indicator updating and doing a database query on every view expose event, which happens on every frame when the scroll indicator fades in/out.
