### ISSUE TITLE
Luakit sometimes follows wrong hints

### ISSUE THREAD

**Issue by asmir-abdulahovic** [aidanholm/luakit#339]
When I type hint characters luakit fucuses wrong hints, like seen in the picture. Same behavior happens even without changing the default hint charset. There is nothing relevant in the console output and the problem occurs rarely and I can't see any usage pattern which triggers this.
(I've pulled latest version)
I've hope you can reproduce this, also I'll make a video if you want to.

![luakit_follow_prob](https://cloud.githubusercontent.com/assets/1333891/26279375/6108e168-3db2-11e7-8e70-a767bd5e78b3.png)

**Comment by aidanholm** [comment]
Your filter is "da", and all of the hinted links contain "da" as part of the text :)
This behavior is controlled by `follow.pattern_maker`. By default it is set to `follow.pattern_styles.match_label_re_text`, which filters by the hint label and the element text. You may want to set `follow.pattern_maker = follow.pattern_styles.match_label` in your configuration, which will cause filtering to only match the hint label.

**Comment by asmir-abdulahovic** [comment]
Oh, this is new to me and I've used vim like browsers for a while. :) Sorry for the false alarm and thanks for explaining.

**Comment by aidanholm** [comment]
No problem! The current documentation for this is particularly terrible; I'll have to fix that at some point.
