### ISSUE TITLE
Can't display more than 100 bookmarks

### ISSUE THREAD

**Issue by izobilje** [aidanholm/luakit#347]
`luakit://bookmarks/` displays only first 100 bookmark entries.
In file `bookmarks_chrome.lua`, there is a support for bookmark pages (opts.page variable), but no button on bookmark page takes advantage of that.

(workaround: increase number in `local limit, page = opts.limit or 100, opts.page or 1`)

**Comment by aidanholm** [comment]
Congratulations, you're probably the first luakit user to have more than 100 bookmarks!

Also, yeah, that sounds like a bug.

**Comment by aidanholm** [comment]
That should be fixed now; feel free to reopen this issue if it's still not working.
