### ISSUE TITLE
please provide ppa

### ISSUE THREAD

**Issue by vitaly-zdanevich** [aidanholm/luakit#354]
Or maybe `snap` package or at least compiler binary for `releases` - I have problem with building of `lfs`.

**Comment by aidanholm** [comment]
A PPA would allow me to provide packages for LFS as well as Luakit, but they seem to be Ubuntu-only. A snap package would fix your problem, as snap packages contain all dependencies. Luakit depends on WebKitGTK+, however, and a security update of WebKitGTK+ without a corresponding Luakit snap package update would leave users vulnerable.

I'm not sure how a compiled binary would help you if you're having problems installing a dependency. Unless you mean a compiled binary with LFS and other dependencies baked into it?

How are you trying to install LFS? Have you tried using luarocks?

**Comment by vitaly-zdanevich** [comment]
Thank you for help, I successfully installed luarocks and LFS but for Ubuntu 14.04 too many manual dependency resolving to install webkit2gtk-4.0

I need to try to migrate from Ubuntu with old packages to ArchLinux... Too many problems to have current version of the software without upgrading the whole system and also after every upgrade I need remove apps like Tetris and Thunderbird :)

Think about docker-image :)
