### ISSUE TITLE
Use prefered `install` command instead of `cp` and other `chmod`

### ISSUE THREAD

**Issue by groolot** [aidanholm/luakit#371]
In the `Makefile`, the `install` target rule uses a mix of `install`, `cp`, `chmod` commands.

The prefered use to comply with the Debian packaging (which is my goal) is to use `install`wherever possible.

**Comment by aidanholm** [comment]
Could you refer me to documentation for these guidelines? I found https://www.debian.org/doc/debian-policy/, but didn't see anything about using `install`.

**Comment by groolot** [comment]
Doc I use is https://www.debian.org/doc/manuals/maint-guide/modify.html

**Comment by aidanholm** [comment]
Thanks!
