### ISSUE TITLE
F: initialize_web_extensions_cb:145: Cannot access luakit extension '/usr/share/luakit/luakit.so': Permission denied

### ISSUE THREAD

**Issue by groolot** [aidanholm/luakit#384]
Since b2a8ed9616dec2ce0728c7b15886e0d97709070f execution failed because of bad permissions on `luakit.so`

**Comment by groolot** [comment]
This happened while compiled and installed as a Debian package. Do you experience the same behavior in vanilla installation?

**Comment by groolot** [comment]
# Issue
`luakit.so` can't be accessed without permissions `755`. The user has to have `r-x` on it.

# Reason
When the Debian package is created, file permissions are modified by the helper script so that the `install` call do not results as expected.
Then, when installed, only `/usr/bin/luakit` file is executable. `/usr/share/luakit/luakit.so` is not executable.

# Workarounds
 * Changing `install` parameters in `Makefile` :-1: 
 * Manually set permissions :-1: 
 * Retrieve commit that verify the `luakit.so` existence:
```
$ git log -SX_OK
6f1e8badaa68b3d64bc60eb762230ac2e9b3f3d0
```

# Solution
As the #174 is a real fix, it introduces the execution flag on `luakit.so` to be verified. Is it really needed? A shared library does not have to be executable, does it?
Then, modify the https://github.com/aidanholm/luakit/blob/develop/ipc.c#L139 and remove ` | X_OK` should fix this issue.

**Comment by aidanholm** [comment]
Looks great, thanks!

**Comment by ivanbalashov239** [comment]
@aidanholm  have the same issue with package aur/luakit-git 
look like you maintain it
Also, if i understood correctly, you already merged this fix to develop branch.
I've couldn't find out why it's still not working, so could you check it?

**Comment by aidanholm** [comment]
Current `develop` branch a23da9aa works fine for me via AUR. To help with debugging, please copy-paste the following:
 - the luakit log up to and including the error
 - the output of `luakit --version`
 - the output of `ls -l /usr/share/luakit/luakit.so`

**Comment by ivanbalashov239** [comment]
@aidanholm 
i have no idea what've changed, but it's builded normally and works well.
I think the issue should be closed.

**Comment by aidanholm** [comment]
Glad to hear!
