### ISSUE TITLE
Unfork?

### ISSUE THREAD

**Issue by mason-larobina** [aidanholm/luakit#388]
Heya Aidan, 

I don't have time for Luakit anymore but still have haven't handed off control of luakit/luakit. I've looked over some of the changes here and I'm impressed to see luakit receive a second wind.

Access is yours if you would like it :)

**Comment by aidanholm** [comment]
Hey,

Thank you for all of your work creating luakit in the first place; without that I wouldn't have much to work with! I'd be very happy to unfork as you suggest; but I have a few issues that came to mind:

 - **Compatibility**: people cloning from luakit/luakit may be expecting a version of luakit compatible with their existing installation. Not likely to be a huge problem, given that the last commit was around a year ago; still, I'm not sure what the clone stats are like.

   One contributor is helping to ready the repo for Debian packaging; I'm not sure what other packages exist, whether they are directly derived from luakit/luakit, or how heavily they are in use, but there are compatibility concerns there as well.

 - **Stability**: there's still a few showstopper bugs around (#382 is a good example). I've been breaking compatibility a fair bit in some places, and I forsee the need to do so a few more times to implement desired features.

 - **luakit-plugins and luakit.org**: If we unfork into luakit/luakit, it'd be confusing to keep luakit-plugins or the website outdated.

 - **Outdated wiki**: Not sure what we can do there, except stick "warning: possibly outdated" on all the pages in big red letters.

Any thoughts?

**Comment by aidanholm** [comment]
And would this imply transfer of ownership of the luakit organization? I'm relatively inexperienced in how GitHub handles such things :)

**Comment by mason-larobina** [comment]
> Thank you for all of your work creating luakit in the first place; without that I wouldn't have much to work with!

Glad you're enjoying it! :)

> Compatibility

I wouldn't worry about this much for the moment. It's a bigger priority to get off webkit1 & revive the project for the people/projects still using it.

> Stability

I've only ever considered this a show-stopper for a release. Otherwise the develop branch has occasionally existed in a semi-broken state.

> luakit-plugins

Perhaps these should have been in-lined into the luakit repo back in the day. People can update them if they miss them. It would be a burden to consider this blocking. We could update the luakit-plugins repo to say it "only works with luakit <= 2012 & contributors welcome".

> luakit.org

I'm happy to continue paying for luakit.org and pointing to the luakit github docs. Access to the repo means access to the github pages too (it's the gh-pages branch).

> imply transfer of ownership of the luakit organization

I'm still happy to sponsor (re costs for luakit.org). Orgs can contain many people. I was initially suggesting just adding you as a member with write access (I don't know what the org controls look like either).

**Comment by aidanholm** [comment]
Okay, that all sounds good. I'd forgotten about the domain costs; thanks for continuing to handle that! Write access to luakit/luakit would certainly be enough to get the main repo updated and get things rolling.

**Comment by groolot** [comment]
This sounds like abeautiful day for the luakit rebirth!
I'm requesting the Debian package handling to Debian org. and Clint Adams (that was the last package maintainer before Orphaning it).
See #383 for more.

**Comment by groolot** [comment]
Then, @mason-larobina, can you give me write access to the `debianization` branch inside `luakit/luakit`, according to @aidanholm of course?

**Comment by aidanholm** [comment]
@groolot As far as i can see, GitHub doesn't provide branch-level access permission granularity. @mason-larobina could add a debianization team in the luakit org with access to a separate repo and add you. I cannot do this myself as I believe it requires org ownership to add/modify teams. Alternatively, I could create a new debianization repo and add you as an outside collaborator to that repo. I'm not sure what access rights you'd have, but the docs suggest that you could be be restricted to that repository only.

**Comment by mason-larobina** [comment]
I've changed the default org member permissions to Admin (read, write, create repos & add new members).

It should also allow adding & manipulating teams. Teams look like the only way to selectively add write permissions to individual repos.

I'll let you two figure out the team & repo setup :)

**Comment by aidanholm** [comment]
I've created three teams; one for admin, one for dev, and one for debian builds. Unfortunately without being an organization owner I cannot invite people, but I can't be an owner without being able to access billing information, which is obviously undesirable. @mason-larobina with the current setup if you change the member permissions back to Read, I should be able to administrate the current repos; not sure about new ones, so I may need to pester you again at some point :)

**Comment by mason-larobina** [comment]
Done

re: pestering, no problems :)

**Comment by Dieterbe** [comment]
<3

**Comment by aidanholm** [comment]
@mason-larobina Do you happen to know who is an op for the #luakit IRC channel?

**Comment by mason-larobina** [comment]
I've recovered my oftc account and updated the topic. Let me know if you want op status :)

**Comment by aidanholm** [comment]
That'd be great! I'm `aidanh`.

**Comment by mason-larobina** [comment]
17:59:52    oftc  -- | MSG(chanserv): access #luakit add aidanh chanop
17:59:53    oftc  -- | ChanServ (services@services.oftc.net): aidanh added to #luakit access list as CHANOP.

Done ^^

**Comment by aidanholm** [comment]
Cheers!
