### ISSUE TITLE
Use functions in search engines.

### ISSUE THREAD

**Issue by zappathustra** [aidanholm/luakit#396]
Defining search engines as strings is sometimes too limited, e.g. when you want to fill multiple fields at once (say, book title and author on biblio.com). The Conkeror browser uses "webjumps", i.e. search engines than can be defined as strings (as Luakit already does) or functions.

The modification is actually quite trivial: in a nutshell, `string.format(engine, terms)` should be replaced by `type(engine) == "function" and engine(terms) or string.format(engine, terms)` in window.lua (you also need the modification for the case where there are no other arguments beside the engine).

(I already use it myself; just thinking it would be a convenient feature and it would keep my window.lua file in sync!)

**Comment by aidanholm** [comment]
I've added support for this. Note that search engine functions are called with multiple arguments, one for each word in the search term. So `:open bib title Foo Bar` will call the handler with arguments `("title", "Foo", "Bar")`. Also, no escaping is performed automatically. So the implementation is a little different to yours. If you find any problems with this approach, feel free to comment!

**Comment by zappathustra** [comment]
Great!
Two remarks:

- You didn't deal with the case where there is no argument (i.e. only the search engine is given); I think it should be done, for consistency, and also because it can be useful.
- I don't use space to delimit arguments (some of my functions check for commas and use that); maybe it's just a matter of preference, but I can imagine more cases with one argument with multiple terms (e.g. `:open bib this is a title`) than with as many arguments as there are terms (e.g. `:open bib one_word_title one_word_author`). I'd personally vote for commas as separators, but maybe the code should be agnostic and pass everything as one argument, and then users can define their own functions to possibly detect multiple arguments?

Anyway, thank you very much!

**Comment by aidanholm** [comment]
- Actually the case with no argument is handled because `terms` becomes an empty string, and `unpack(args)` will give no arguments to a handler function.
 - I've changed it to pass everything as one argument.

**Comment by zappathustra** [comment]
Sorry about the no argument case, I had missed the previous modification on line 644 (which now excludes search engines). So it's just great!
