### ISSUE TITLE
test fail

### ISSUE THREAD

**Issue by SolarAquarion** [aidanholm/luakit#397]
luajit: error loading module 'tests.util' from file './tests/util.so':
        ./tests/util.so: undefined symbol: g_dir_make_tmp
stack traceback:
        [C]: at 0x00452b30
        [C]: in function 'require'
        tests/run_test.lua:15: in main chunk
        [C]: at 0x00404680
make: *** [Makefile:121: run-tests] Error 1

I'm doing a initial version of the check function of the pkgbuild

**Comment by aidanholm** [comment]
Probably caused by an issue in the `tests/util.so` target in the Makefile, unless your GLib is < 2.30 (unlikely).

**Comment by SolarAquarion** [comment]
let me try rebuild glib2

**Comment by SolarAquarion** [comment]
that's weird

**Comment by SolarAquarion** [comment]
i installed the git version of glib2

**Comment by aidanholm** [comment]
My version is 2.52.2+9+g3245eba16-1

**Comment by aidanholm** [comment]
Is this still a problem?

**Comment by aidanholm** [comment]
Turned out to be a linker problem; this is fixed now with the merge of https://github.com/luakit/luakit/pull/418

**Comment by aidanholm** [comment]
BTW I'm working on the luakit/luakit upstream repository now and will stop pushing to this one soon.
