### ISSUE TITLE
Issues with maps.google.com

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#4]
- It only allows LITE mode (epiphany does not show the warning/flash but I can't enter 3D-mode, which is weird). I did not yet try to look into it, but probably only WebGL needs to be activated.
- I can't pann/zoom the view with my mouse. When I click in the view the text/ibeam cursor appears (as long as I keep pressing the mouse button)
- The search box never gets input focus, so searching maps is not possible at all.

I am (still ;)) using webkit-gtk-2.12.2 and gtk+-3.20.2.

**Comment by aidanholm** [comment]
I've pushed some changes that expose the WebGL setting for WebKit1 builds (for some reason it was disabled entirely) and set it to enabled by default. If you've customized webview.lua you'll need to copy the changes over. With WebGL enabled, Google Maps seems to be working fine for me---let me know if this fixes it for you.

**Comment by ff2000** [comment]
Well, after an hour of googling (and reading bug reports), and trying things without success I found a workaround ;)
`globals.useragent = "Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"`
So I basically need to cheat to convince google maps to serve the correct javascript :/ Does the default luakit useragent work for you or did you also change it?
Besides the non-visible cursor all three issues are resolved!

**Comment by aidanholm** [comment]
Ah, that's irritating; yes, I changed it to `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36`, so that's probably why it works for me. At some point I'll do some experimenting and see if there's one particular UA component that's causing the issue. An alternative workaround could be to include a domain_props rule just for Google Maps in the default config.

**Comment by ff2000** [comment]
Yay, useragents are so cute! They can produce completely unexpected things like completely breaking your browser...
The useragent-string I posted above caused #26 - using one from a recent chrome-version and bugzilla works again. This is really more sensible than I would have thought, and configuring them in the default config might break more setups than we could think of...
Using separate rules just for specific pages sounds reasonable.

**Comment by aidanholm** [comment]
Fixed in #70
