### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ghost** [aidanholm/luakit#403]
What do the following from rc.lua do ? Where can I find more info on these ?

require "follow_selected"
require "go_input"
require "go_next_prev"
require "go_up"

I don't program. If a search engine has another % except %s in globals.lua then it doesn't work.
For example I'm using https://searx.me/?q=!go%20%s so it only shows google results.

**Comment by aidanholm** [comment]
There's documentation for all of these at `luakit://help/doc/index.html`, but briefly: `follow_selected` opens links in the selected text (handy if your search result contains a link), `go_input` focuses a text box and switches to insert mode, `go_next_prev` automatically detects "next page" and "prev page" links and gives you key bindings for clicking them, and `go_up` goes up one level in the URI (e.g. `foo.com/bar/baz/` -> `foo.com/bar/`.

You need to escape the other %: the escape character is also %, so it should look like `https://searx.me/?q=!go%%20%s`.

**Comment by ghost** [comment]
Thanks for the help. Is there any way to configure the keys used for hints/follow ? I'd like them to be 'asdfghjkl' instead of numbers. I couldn't find anything in the configs.
And I have another question regarding domain settings:

globals.domain_props = {
    ["all"] = {
        enable_webgl            = false,
        enable_scripts          = false,
        enable_plugins          = false,
        -- zoom-text-only          = true,
    },
    ["youtube.com"] = {
        enable_scripts = true,
        enable_plugins = true,
    }, 
}

Do single domains keep options which are not specified from all ? For example does youtube.com inherit the enable_webgl = false from all ?

**Comment by aidanholm** [comment]
See `luakit://help/doc/modules/follow.html` for using a custom character set for hints. The documentation there is (which is admittedly sparse) is all under `luakit://help/`.

Yes, they do. Every time a page is loaded, rules from domain_props are merged into a single set, with more-specific rules ("youtube.com") overriding low-specificity rules ("all"). So if you don't specify `enable_webgl` in your youtube rules, it'll fall back to the "all" rules.

**Comment by ghost** [comment]
I was honestly confused a little at first but then I found this https://github.com/aidanholm/luakit/issues/312 which cleared things up.
Thanks for all the help.
I don't have any questions right now but would it be okay to live this open for a few more days so I accumulate some luakit usage ?

**Comment by aidanholm** [comment]
Sure, feel free. Glad I could help!

**Comment by ghost** [comment]
Is enable_scripts and alias for enable_javascript from https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html

I'm trying to enable javascript on 4chan and I can't seem to get it right. That catalog is practically the only think i even need javascript enabled for.

    ["boards.4chan.orgj"] = {
        enable_scripts          = true,
        enable_javascript       = true,
    },
    ["4chan.orgj"] = {
        enable_scripts          = true,
        enable_javascript       = true,
    },

**Comment by aidanholm** [comment]
Yep, it's an alias from the WebKit 1 days; I noticed that earlier today while documenting `domain_props.lua` actually. I'm planning to deprecate it though.

Couple of points: 1) your "boards.4chan.org" rules are completely overrided by your "4chan.org" rules, 2) specifying both `enable_scripts` and `enable_javascript` is redundant, and 3) your rules end in "orgj" not "org", which is probably the cause of your trouble. Try this: `["4chan.org"] = { enable_scripts = true }`. You'll also need `["all"] = { enable_scripts = false }` of course.

**Comment by ghost** [comment]
I included boards.4chan.org because I thought domains might be managed in a similar way to /etc/hosts but yes, the 'j' at the end of the org was the culprit. Thank you for the detailed explanation and for all the help.
I'm going to close this now since I've pretty much configured luakit to a perfect personal preference state.

**Comment by aidanholm** [comment]
You're welcome, glad I could help!
