### ISSUE TITLE
Example of connecting to the "init" signal?

### ISSUE THREAD

**Issue by zappathustra** [aidanholm/luakit#405]
Using "webview.init_funcs" is deprecated, and users should "connect to the 'init' signal on the webview module". Is it possible to have an example of that? Signals are quite opaque to me, and I may not be the only one...

**Comment by aidanholm** [comment]
Instead of 
```
webview.init_funcs.my_cool_init_func = function (view)
    -- Do stuff with view here
end
```
do
```
webview.add_signal("init", function (view)
    -- Do stuff with view here
end)
```
The main reason for this is to avoid possible name collisions, if two modules try to set an init function with the same name.

**Comment by zappathustra** [comment]
Simple as that. Great, thank you!

**Comment by aidanholm** [comment]
No problem!
