### ISSUE TITLE
Bindings for mouse buttons 4 and 5 not recognized

### ISSUE THREAD

**Issue by izobilje** [aidanholm/luakit#409]
Although bindings in /usr/share/luakit/lib/binds.lua exist, zooming and scrolling horizontally with wheel (Ctrl or Shift + buttons 4 and 5) doesn't work, only scrolling vertically (default behaviour).

Now I use luakit-git on Arch linux v. 2017.07.26.r164.gcb6f0604, but they also didn't work for me a month ago, using r3575.70ce9dfc.

As a test, I've tried to make custom bindings for Ctrl+mouse button 1, and it works. Also I've checked with xev program that mouse wheel indeed sends button 4 and 5 clicks.

**Comment by aidanholm** [comment]
Thanks for reporting this! I've added a fix at 13610478; it'll only work for buttons 4 and 5, i.e. not for horizontal scrolls, and not for smooth scrolls.

BTW I'm mostly pushing to the main luakit repository, and will stop pushing to this one soon.
