### ISSUE TITLE
luakit.webkit*version are wrong

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#70]
They return the webkitgtk package version (e.g.2.12) when they should return the actual WebKit version (e.g. 602.1).

**Comment by aidanholm** [comment]
To the best of my knowledge, these are the only WebKit version numbers available; WebKitGTK version numbers appear to be on a separate track, but I haven't found much information on this.

**Comment by ff2000** [comment]
Tracked it down... There is no way to get the webkit version. It's passed as DEFINE in cmake/OptionsGTK.cmake and used directly in WebCore/platform/gtk/UserAgentGtk.cpp
The only way to get it would be parsing the standardUserAgent and extract the numbers. Or simply use standardUserAgentForURL and append luakit/VERSION. Or ask for exposure of those MINOR/MAJOR_VERSION in the API e.g. propose a patch...

**Comment by aidanholm** [comment]
Is there any reason why returning that version number would be preferable to the package version?

**Comment by ff2000** [comment]
On Fri, 08 Jul 2016 09:12:31 -0700, Aidan Holm notifications@github.com wrote:

> Is there any reason why returning that version number would be preferable to the package version?

The default user agent also returns "Safari/602.1" and I can imagine checks against certain Safari versions.
But I am not a web developer, I just know little about all that stuff ;) So I might be wrong and how luakit currently handles this is just fine.

**Comment by ff2000** [comment]
Also have a look at https://bugs.webkit.org/show_bug.cgi?id=133403 (linked in Source/WebCore/platform/gtk/UserAgentGtk.cpp:141) Probably a reason to stick with the defaults from webkitgtk (+append luakit). I set it to an empty string now in my globals.lua and it seems to work.

**Comment by aidanholm** [comment]
One issue with customizing the user agent is that it makes fingerprinting really easy---it's very easy to construct a user agent by accident that no-one else has. So I'd prefer to remove construction of a Luakit-specific user agent entirely from `config/globals.lua`. Using the default UA should contain the correct WebKit version number, preventing sites from breaking, and the default UA should be common enough so as to be less useful for fingerprinting. Should users prefer, they may of course get/set the UA themselves.

**Comment by aidanholm** [comment]
Fix pushed in e21a8a3. Fixes #4 and #26. Still possible to set a custom user agent; it's just not done by default anymore.
