### ISSUE TITLE
Proxy setting is ignored

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#74]
what I do:
1. in command line monitor any connections to the proxy port:
   "LC_ALL=C nc -vl -s 127.0.0.1 -p 3128 </dev/null" 
   it hangs with "listening on [127.0.0.1] 3128 ..."
2. in luakit:
   2.1. In normal mode type ":proxy", then 'a'
   2.2. ":proxy " prompt appears, type "local 127.0.0.1:3128"
   2.3. it goes back to normal mode, type ":proxy", 'j', 'j', Return
   2.4. information "Using proxy: local (127.0.0.1:3128)" appears
   2.5. type 'o' and then "github.com"

what I see:

github page is displayed, netcat does not indicate any connections

what I expect:

luakit tried connecting to the configured proxy and fail

tested locally built luakit from 4c1f408 commit (webkit2 branch)

**Comment by aidanholm** [comment]
Thank you for the report. In WebKit 2, the SoupSession is now in the WebKit Network process, and there is no API to access it, nor is there an API to modify the proxy URI. One related bug report is https://bugs.webkit.org/show_bug.cgi?id=128674. I have removed all support for WebKit 1, so unfortunately until the corresponding API is implemented in WebKit the `:proxy` command cannot be fixed.

If you use GNOME, it should be possible to specify proxy settings globally somewhere within GNOME's settings. Alternatively, you may be able to use wrapper programs such as tsocks.

**Comment by ff2000** [comment]
On Sat, 09 Jul 2016 04:03:53 -0700, Aidan Holm notifications@github.com wrote:

> Thank you for the report. In WebKit 2, the SoupSession is now in the WebKit Network process, and there is no API to access it, nor is there an API to modify the proxy URI. One related bug report is https://bugs.webkit.org/show_bug.cgi?id=128674. I have removed all support for WebKit 1, so unfortunately until the corresponding API is implemented in WebKit the `:proxy` command cannot be fixed.
> 
> If you use GNOME, it should be possible to specify proxy settings globally somewhere within GNOME's settings. Alternatively, you may be able to use wrapper programs such as tsocks.

You don't even need GNOME, simply export http_proxy and https_proxy and you are done: `export https_proxy="http://127.0.0.1:8118"`

**Comment by Ygrex** [comment]
thank you, I tried running a separate luakit instance with the environment set (it requires -U parameter), authenticated github session had to be established in it separately; any way to make them cooperate with each other?

**Comment by aidanholm** [comment]
Do you mean have two separate instances of luakit (with -U), but have them share session state (cookies, current logins, etc)? That's not possible as each separate instance of luakit has separate network processes.

**Comment by aidanholm** [comment]
Proxy support in WebKit 2 is likely to return at some point: see https://bugs.webkit.org/show_bug.cgi?id=128674

**Comment by aidanholm** [comment]
According to https://trac.webkit.org/wiki/WebKitGTK/Roadmap, the relevant proxy API (above issue) will be implemented in WebKit2GTK 2.16

**Comment by aidanholm** [comment]
Proxy support is implemented at f2e9417c, merged into `develop`. It requires building and running with WebKitGTK 2.16 or later, which is currently in the `gnome-unstable` repository if you're using Arch.

Glad to have this one finally closed!
