### ISSUE TITLE
:open, :history etc.: support queries with multiple words

### ISSUE THREAD

**Issue by ff2000** [aidanholm/luakit#75]
currently `:open gentoo fo<TAB>` expands to `:open gentoo http://focus.de`, the last word only is considered for completion. As a result `<RET>` opens a google search for `gentoo http://focus.de` as it's not a valid URL.
Expected behaviour: select only matching entries like `http://forums.gentoo.org` and ignore anything else that matches only one search term like http.gentoo.org or forums.kde.org.

**Comment by aidanholm** [comment]
Pretty sure I've experienced this myself. Quite annoying.

**Comment by aidanholm** [comment]
Fixed as of 01c62d7, although still not perfect; ":open arch wiki<tab>" will not match "Foo - Arch Wiki" for example, although ":open archwiki<tab>" will.

**Comment by aidanholm** [comment]
Seems to have broken `<RET>` for some reason

**Comment by aidanholm** [comment]
Fixed, again
