### ISSUE TITLE
«Open Link in New Window» does not open new window

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#77]
What I do:
1. Open URL: https://webkitgtk.org/security.html
2. Mouse right button click on the top-most URL in the list, it reads "WebKitGTK+ Security Advisory WSA-2016-0004" today
3. "Open Link in New Window" in the pop-up menu

What I see:

new tab opens with the URL

What I expect:

new window opens with the URL

**Comment by aidanholm** [comment]
I've noticed this myself. The `populate-popup` signal can be used to append items to the context menu; it'd be nice to pass the predefined context menu to the signal handler for modification, as well as addition. This would allow a signal handler to fix this.

**Comment by aidanholm** [comment]
Fixed as of 3deeff8
