### ISSUE TITLE
Numpad navigation does not work

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#79]
What I do:
1. go to https://github.com/aidanholm/luakit/issues
   it does not fit my screen height, alternatively one can resize the luakit window so
2. press down arrow on a numpad (KP_Down)

What I see:

viewable area does not scroll

What I expect:

viewable area should scroll down as if regular down key is pressed

tested other numpad keys for navigation, they all ignored

**Comment by aidanholm** [comment]
Thanks for the fix
