### ISSUE TITLE
webkit crashes on launch

### ISSUE THREAD

**Issue by JR1994** [aidanholm/luakit#91]
The error has gone away after your changes, but the browser is till crashing. I ran luakit in debug mode and am posting the log file.

[luakit-debug.txt](https://github.com/aidanholm/luakit/files/364247/luakit-debug.txt)

**Comment by aidanholm** [comment]
Which commit are you building from? In the log I see that the web process is crashing; is it just the web process or is the main luakit process crashing as well? Are there any session files in `$XDG_DATA_HOME/luakit/session`?

**Comment by JR1994** [comment]
On 07/14, Aidan Holm wrote:

> Which commit are you building from? In the log I see that the web process is crashing; is it just the web process or is the main luakit process crashing as well? Are there any session files in `$XDG_DATA_HOME/luakit/session`?
> 
> This the info you are looking for:

GIT update -->
   repository:               git://github.com/aidanholm/luakit.git
   at the commit:            eb75747d26e5640adc4a8994c8f49107d6faf4b8
   branch:                   webkit2
   storage directory:
        "/usr/portage/distfiles/egit-src/luakit.git"
         checkout type:            bare repository
         Cloning into
        '/var/tmp/portage/www-client/luakit-9999/work/luakit-9999'...

The web process is crashing. Luakit stays open. The home page loads for
a few seconds then a crash page loads.

I am also getting this

rican-linux@gentoo-ppc ~ $ ls $XDG_DATA_HOME/luakit/session
ls: cannot access /luakit/session: No such file or directory

I know this is my $HOME/.local/share and here is what I have there

ls .local/share/luakit/
bookmarks.db  cookies.db  history.db  recovery_session  styles.db

Anything else you need?
Herminio

**Comment by aidanholm** [comment]
Try removing `~/.local/share/recovery_session` before starting luakit. Otherwise, is it possible to get a core dump of the WebKit web process? Since eb75747, logging from the web process is done via IPC with the main luakit process; it's possible this change is causing a crash, although unlikely, since your log shows messages from the web process working fine.

**Comment by JR1994** [comment]
On 07/14, Aidan Holm wrote:

> Try removing `~/.local/share/recovery_session` before starting luakit. Otherwise, is it possible to get a core dump of the WebKit web process? Since eb75747, logging from the web process is done via IPC with the main luakit process; it's possible this change is causing a crash, although unlikely, since your log shows messages from the web process working fine. 
> 
> Removing the recovery_session file did not help things at all. How would
> I get a core dump of the webkit web process? Do I need to have the
> webkit debugging symbols and try to luakit in gdb again?

Herminio

**Comment by aidanholm** [comment]
Ah, in that case I'll close this issue. For completeness, obtaining a core dump varies by distribution; systemd-based systems use coredumpctl, for example. No webkit debugging symbols are needed since the luakit-specific shared library linked into the web process has its own debug symbols.
