### ISSUE TITLE
Location in status bar does not always reflect updated location.

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#96]
What I do and see:
1. ./luakit -U 'https://github.com/aidanholm/luakit'
2. hover over «Pull requests» link, status bar displays the associated URL correctly
3. click «Pull requests», wait until the page loaded
4. note status bar is not updated showing the old location: https://github.com/aidanholm/luakit
5. reload the page pressing 'r', note the status bar shows the correct location now: https://github.com/aidanholm/luakit/pulls

What I expect:

status bar shows the current location any time

**Comment by aidanholm** [comment]
This is github specific; something to do with how it loads pages like a single-page app. Root cause is in C code, with the uri property not being updated properly.

**Comment by aidanholm** [comment]
I've removed the webview uri property wrapper at a43f97c; not sure what it was there for, so removing it might cause other functionality to break. Seems fine so far though.
